name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title format
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure the types of commits allowed
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # Require a scope (e.g., "feat(api): add new endpoint")
          requireScope: false
          # Subject should not be sentence-case, start-case, pascal-case, upper-case
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          # Validate that the entire PR title follows conventional commits
          validateSingleCommit: false
          # Ignore dependabot PRs
          ignoreLabels: |
            dependencies
            bot

      - name: Comment on PR if title is invalid
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload.pull_request.title;
            const body = `
            ## ❌ PR Title Check Failed

            The PR title \`${title}\` doesn't follow the [Conventional Commits](https://www.conventionalcommits.org/) specification.

            ### Required Format
            \`\`\`
            <type>[optional scope]: <description>
            \`\`\`

            ### Examples
            - \`feat: add C++ bindings for IRremoteESP8266\`
            - \`fix(api): correct protocol detection for Fujitsu\`
            - \`docs: update deployment guide\`
            - \`refactor(core): simplify protocol matching\`
            - \`test: add integration tests for Tuya codes\`

            ### Allowed Types
            - **feat**: A new feature
            - **fix**: A bug fix
            - **docs**: Documentation only changes
            - **style**: Changes that don't affect code meaning (formatting, etc.)
            - **refactor**: Code change that neither fixes a bug nor adds a feature
            - **perf**: Performance improvement
            - **test**: Adding missing tests or correcting existing tests
            - **build**: Changes to build system or dependencies
            - **ci**: Changes to CI configuration files
            - **chore**: Other changes that don't modify src or test files
            - **revert**: Reverts a previous commit

            Please update your PR title to match this format.
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
